Repository freshworks/marketplace-sample-apps, pull requests merged in 2019-10, with the labels that each got.

#41 Code of Conduct
  CODE_OF_CONDUCT.MD
Labels: needs-review

#42 Create Contribution Guidelines
  CONTRIBUTING.MD
Labels: needs-review

#39 Advanced data storage app
  Freshdesk/v2/advanced_data_storage_app/README.md
  Freshdesk/v2/advanced_data_storage_app/app/asset/icon.svg
  Freshdesk/v2/advanced_data_storage_app/app/js/app.js
  Freshdesk/v2/advanced_data_storage_app/app/js/create_alias.js
  Freshdesk/v2/advanced_data_storage_app/app/js/find_alias.js
  Freshdesk/v2/advanced_data_storage_app/app/templates/create_alias.html
  Freshdesk/v2/advanced_data_storage_app/app/templates/find_alias.html
  Freshdesk/v2/advanced_data_storage_app/app/templates/index.html
  Freshdesk/v2/advanced_data_storage_app/config/iparam_test_data.json
  Freshdesk/v2/advanced_data_storage_app/config/iparams.json
  Freshdesk/v2/advanced_data_storage_app/manifest.json
Labels: freshdesk, needs-review, work-in-progress

#27 simple api app - Phase 2 complete
  Freshdesk/v2/simple_request_app/app/app.js
Labels: needs-review

#31 Interceptingeventsapps
  Freshdesk/v2/.gitignore
  Freshdesk/v2/intercepting_events_app/README.md
  Freshdesk/v2/intercepting_events_app/app/app.js
  Freshdesk/v2/intercepting_events_app/config/iparam_test_data.json
  Freshdesk/v2/intercepting_events_app/screenshots/2.png
  Freshdesk/v2/intercepting_events_app_2/app/app.js
  Freshdesk/v2/your_first_app/app/app.js
  Freshdesk/v2/your_first_app/app/style.css
  Freshdesk/v2/your_first_app/app/template.html
Labels: freshdesk, needs-review

#25 yourfirstserverlessapp - Phase 2 complete
  Freshdesk/v2/enhanced_data_storage_app/app/app.js
  Freshdesk/v2/simple_events_api_app/app/app.js
  Freshdesk/v2/your_first_serverless_app/server/server.js
  Freshdesk/v2/your_first_serverless_app/server/test_data/onTicketCreate.json
Labels: freshdesk, under-review, work-in-progress

#82 [Enhancement] Changed comments to JSDoc standards
  Freshdesk/v2/ticket_top_navigation_app/app/app.js
  Freshdesk/v2/ticket_top_navigation_app/app/startTimer.js
Labels: needs-review
