Repository freshworks/marketplace-sample-apps, pull requests merged in 2020-10, with the labels that each got.

#202 Restructure directory for Quick Links app
  Demo-Apps/quick_links_app/README.md
  Demo-Apps/quick_links_app/app/index.html
  Demo-Apps/quick_links_app/app/scripts/app.js
  Demo-Apps/quick_links_app/app/scripts/jquery.tmpl.min.js
  Demo-Apps/quick_links_app/app/scripts/modal.js
  Demo-Apps/quick_links_app/app/styles/images/delete.svg
  Demo-Apps/quick_links_app/app/styles/images/edit.svg
  Demo-Apps/quick_links_app/app/styles/images/icon.svg
  Demo-Apps/quick_links_app/app/styles/styles.css
  Demo-Apps/quick_links_app/app/views/modal.html
  Demo-Apps/quick_links_app/manifest.json
  Demo-Apps/quick_links_app/screenshots/app_face.png
  Demo-Apps/quick_links_app/screenshots/manage_bookmarks.png
Labels: Hacktoberfest

#204 use client.request instead of ajax in the custom_installation_page_app
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/config/iparams.html
Labels: Hacktoberfest

#210 fix: refactor tickets_close_interceptor app
  .gitignore
  Freshworks-Samples/Freshdesk/tickets_close_interceptor/app/app.js
Labels: Hacktoberfest

#205 Restructure the Pomodoro App folder structure and fix it
  Freshworks-Samples/Freshservice/Pomodoro/README.md
  Freshworks-Samples/Freshservice/Pomodoro/app/index.html
  Freshworks-Samples/Freshservice/Pomodoro/app/scripts/app.js
  Freshworks-Samples/Freshservice/Pomodoro/app/scripts/mod.js
  Freshworks-Samples/Freshservice/Pomodoro/app/styles/images/freshservice_logo.png
  Freshworks-Samples/Freshservice/Pomodoro/app/styles/images/icon.svg
  Freshworks-Samples/Freshservice/Pomodoro/app/styles/style.css
  Freshworks-Samples/Freshservice/Pomodoro/app/views/mod.html
  Freshworks-Samples/Freshservice/Pomodoro/manifest.json
Labels: Hacktoberfest

#206 Reorganize request_api app
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/app/index.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/app/styles/images/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/app/styles/images/icon.svg
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/app/styles/style.css
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/request_api/manifest.json
Labels: Hacktoberfest, hacktoberfest-accepted

#211 ISSUE: #149
  Freshworks-Samples/Freshservice/conditional_ticket_properties/README.md
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/app.js
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/scripts/app.js
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/styles/images/freshservice_logo.png
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/styles/images/icon.svg
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/styles/style.css
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/template.html
  Freshworks-Samples/Freshservice/conditional_ticket_properties/manifest.json
  Freshworks-Samples/Freshservice/conditional_ticket_properties/screenshots/disable_and_add_note.png
Labels: Hacktoberfest, hacktoberfest-accepted

#209 Fixed issue #201
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/simple_request_app/app/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/simple_request_app/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/simple_request_app/config/iparams.json
Labels: Hacktoberfest

#213 Reorganise: custom_installation page app
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/README.md
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/app/index.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/manifest.json
Labels: Hacktoberfest, hacktoberfest-accepted

#203 Custom installation page
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/config/assets/iparams.css
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/config/assets/iparams.js
  Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app/config/iparams.html
Labels: Hacktoberfest

#217 Added agent-appreciation-app
  Freshworks-Samples/Freshchat/agent-appreciation-app/README.md
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/freshchat_logo.png
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/index.html
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/modal.html
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/scripts/app.js
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/styles/images/award.gif
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/styles/images/icon.svg
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/styles/images/popper.gif
  Freshworks-Samples/Freshchat/agent-appreciation-app/app/styles/style.css
  Freshworks-Samples/Freshchat/agent-appreciation-app/config/iparams.json
  Freshworks-Samples/Freshchat/agent-appreciation-app/manifest.json
Labels: Hacktoberfest, medium

#221 Fixed issue #188
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/app/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/app/styles/images/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/app/styles/images/icon.svg
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/app/styles/style.css
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/app/template.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app/manifest.json
Labels: hacktoberfest-accepted

#220 Workaround fix for navigation of quick links demo app
  Demo-Apps/quick_links_app/app/scripts/app.js
Labels: Hacktoberfest, hacktoberfest-accepted

#219 freshsales-airtable integration
  Freshworks-Samples/Freshsales/airtable/README.md
  Freshworks-Samples/Freshsales/airtable/config/iparam_test_data.json
  Freshworks-Samples/Freshsales/airtable/config/iparams.json
  Freshworks-Samples/Freshsales/airtable/manifest.json
  Freshworks-Samples/Freshsales/airtable/server/lib/handle-response.js
  Freshworks-Samples/Freshsales/airtable/server/server.js
  Freshworks-Samples/Freshsales/airtable/server/test_data/onAppInstall.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onAppUninstall.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onAppointmentCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onAppointmentUpdate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onContactCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onContactDelete.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onContactUpdate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onCustomModuleCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onCustomModuleUpdate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onDealCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onDealDelete.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onDealUpdate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onExternalEvent.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onLeadCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onLeadDelete.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onLeadUpdate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onSalesAccountCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onSalesAccountDelete.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onSalesAccountUpdate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onScheduledEvent.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onTaskCreate.json
  Freshworks-Samples/Freshsales/airtable/server/test_data/onTaskUpdate.json
Labels: Hacktoberfest, hacktoberfest-accepted

#214 Added Freshchat Typescript sample app
  Freshworks-Samples/Freshchat/freshchat-typescript-app/.eslintignore
  Freshworks-Samples/Freshchat/freshchat-typescript-app/.eslintrc.js
  Freshworks-Samples/Freshchat/freshchat-typescript-app/.gitignore
  Freshworks-Samples/Freshchat/freshchat-typescript-app/.prettierrc.json
  Freshworks-Samples/Freshchat/freshchat-typescript-app/README.md
  Freshworks-Samples/Freshchat/freshchat-typescript-app/config/iparams.json
  Freshworks-Samples/Freshchat/freshchat-typescript-app/manifest.json
  Freshworks-Samples/Freshchat/freshchat-typescript-app/package.json
  Freshworks-Samples/Freshchat/freshchat-typescript-app/server/.gitignore
  Freshworks-Samples/Freshchat/freshchat-typescript-app/server/interfaces/.gitignore
  Freshworks-Samples/Freshchat/freshchat-typescript-app/server/src/interfaces/EventPayload.ts
  Freshworks-Samples/Freshchat/freshchat-typescript-app/server/src/interfaces/Marketplace.ts
  Freshworks-Samples/Freshchat/freshchat-typescript-app/server/src/server.ts
  Freshworks-Samples/Freshchat/freshchat-typescript-app/tsconfig.json
  Freshworks-Samples/Freshchat/freshchat-typescript-app/yarn.lock
Labels: Hacktoberfest, hacktoberfest-accepted, medium

#225 Reorganised folders + upd readme
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/app/index.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/app/styles/styles.css
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/config/iparam_test_data.json
Labels: Hacktoberfest, hacktoberfest-accepted

#224 Reorganize advance data storage app
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/index.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/scripts/create_alias.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/scripts/find_alias.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/templates/create_alias.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/templates/find_alias.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/app/templates/index.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app/manifest.json
Labels: Hacktoberfest, hacktoberfest-accepted

#223 improve ticket_background_app #193
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/app/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/app/index.html
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app/screenshots/no_installation_page.png
Labels: Hacktoberfest, hacktoberfest-accepted

#222 Improve react todo app
  Demo-Apps/react_todo_app/Screenshots/App face.png
  Demo-Apps/react_todo_app/app/app.js
  Demo-Apps/react_todo_app/app/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#228 Completed tasks 1,3,4,5,6,7 on simple_events_api_app
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/app/template.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/config/iparam_test_data.json
Labels: Hacktoberfest, hacktoberfest-accepted

#227 Fix: refactor interface_api
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/index.html
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/styles/images/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/styles/images/icon.svg
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/styles/modal1.css
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/styles/style.css
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/app/views/modal.html
  Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api/config/iparam_test_data.json
Labels: Hacktoberfest, hacktoberfest-accepted

#233 fullcontact app added
  Demo-Apps/fullcontact_app/README.md
  Demo-Apps/fullcontact_app/app/app.js
  Demo-Apps/fullcontact_app/app/icon.svg
  Demo-Apps/fullcontact_app/app/modal.html
  Demo-Apps/fullcontact_app/app/style.css
  Demo-Apps/fullcontact_app/app/template.html
  Demo-Apps/fullcontact_app/config/iparams.json
  Demo-Apps/fullcontact_app/manifest.json
  Demo-Apps/fullcontact_app/screenshots/App face 2.png
  Demo-Apps/fullcontact_app/screenshots/App face.png
  Demo-Apps/fullcontact_app/screenshots/modal.png
Labels: Hacktoberfest

#251 [Enhancement] - Remove jQuery from scheduled_events_tutorial app
  Play-Along/Tutorials/scheduled_events_tutorial/app/app.js
  Play-Along/Tutorials/scheduled_events_tutorial/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#254 remove jquery
  Freshworks-Samples/Freshservice/freshsales_integration/app/app.js
  Freshworks-Samples/Freshservice/freshsales_integration/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#232 Get details from Google ads and create leads in Freshsales done
  Freshworks-Samples/Freshsales/Google Leads Integration/README.md
  Freshworks-Samples/Freshsales/Google Leads Integration/config/iparam_test_data.json
  Freshworks-Samples/Freshsales/Google Leads Integration/config/iparams.json
  Freshworks-Samples/Freshsales/Google Leads Integration/manifest.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/createLeads.js
  Freshworks-Samples/Freshsales/Google Leads Integration/server/lib/handle-response.js
  Freshworks-Samples/Freshsales/Google Leads Integration/server/server.js
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onAppInstall.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onAppUninstall.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onAppointmentCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onAppointmentUpdate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onContactCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onContactDelete.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onContactUpdate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onCustomModuleCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onCustomModuleUpdate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onDealCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onDealDelete.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onDealUpdate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onExternalEvent.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onLeadCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onLeadDelete.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onLeadUpdate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onSalesAccountCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onSalesAccountDelete.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onSalesAccountUpdate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onScheduledEvent.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onTaskCreate.json
  Freshworks-Samples/Freshsales/Google Leads Integration/server/test_data/onTaskUpdate.json
Labels: Hacktoberfest, hacktoberfest-accepted

#257 Remove jQuery from requester_info_retriver
  Freshworks-Samples/Freshdesk/requester_info_retriver/app/app.js
  Freshworks-Samples/Freshdesk/requester_info_retriver/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#259 Remove jQuery from notes_reminder
  Demo-Apps/notes_reminder/app/app.js
  Demo-Apps/notes_reminder/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#258 Remove jQuery from simple_datastorage_app
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/simple_datastorage_app/app/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/simple_datastorage_app/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#256 Remove jQuery from tickets_creation_scheduler_app
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/js/index.js
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/js/list_schedule.js
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/js/schedule_detail.js
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/js/util.js
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/templates/index.html
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/templates/list_schedules.html
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/templates/schedule_detail.html
Labels: Hacktoberfest, hacktoberfest-accepted

#264 Fservice show tickets and associated details
  Freshworks-Samples/Freshservice/show_ticket_and_associated_details/app/app.js
  Freshworks-Samples/Freshservice/show_ticket_and_associated_details/app/content.html
  Freshworks-Samples/Freshservice/show_ticket_and_associated_details/app/modal.css
  Freshworks-Samples/Freshservice/show_ticket_and_associated_details/app/modal.js
  Freshworks-Samples/Freshservice/show_ticket_and_associated_details/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#265 Remove jQuery from conditional_ticket_properties
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/scripts/app.js
  Freshworks-Samples/Freshservice/conditional_ticket_properties/app/template.html
Labels: hacktoberfest-accepted

#268 Remove jQuery from multi_config_oath_app
  Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/multi_config_oauth_app/app/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/multi_config_oauth_app/app/template.html
Labels: hacktoberfest-accepted

#267 Fix accidental shadowing in tickets_creation_scheduler_app
  Freshworks-Samples/Freshdesk/tickets_creation_scheduler_app/app/js/list_schedule.js
Labels: hacktoberfest-accepted

#266 Remove jQuery from scheduled_events_sample_app
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/js/index.js
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/js/list_schedule.js
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/js/schedule_detail.js
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/js/util.js
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/templates/index.html
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/templates/list_schedules.html
  Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_events_sample_app/app/templates/schedule_detail.html
Labels: Hacktoberfest, hacktoberfest-accepted

#263 Remove jQuery from enhanced_data_storage_app
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/enhanced_data_storage_app/app/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/enhanced_data_storage_app/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#262 Remove jQuery from instance-api
  Freshworks-Samples/App-Development-Features/Advanced-Features/instance_method/instance_api/app/modal.html
  Freshworks-Samples/App-Development-Features/Advanced-Features/instance_method/instance_api/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#260 Remove jQuery from timer_on_tap
  Freshworks-Samples/Freshdesk/timer_on_tap/app/app.js
  Freshworks-Samples/Freshdesk/timer_on_tap/app/startTimer.html
  Freshworks-Samples/Freshdesk/timer_on_tap/app/startTimer.js
  Freshworks-Samples/Freshdesk/timer_on_tap/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#261 Remove jQuery from onedrive-oauth-app
  Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/onedrive_oauth_app/app/app.js
  Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/onedrive_oauth_app/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted

#255 [ISSUE-236] - Remove jquery from quick_links_app
  Demo-Apps/quick_links_app/app/index.html
  Demo-Apps/quick_links_app/app/scripts/app.js
  Demo-Apps/quick_links_app/app/scripts/jquery.tmpl.min.js
  Demo-Apps/quick_links_app/app/scripts/modal.js
  Demo-Apps/quick_links_app/app/views/modal.html
Labels: Hacktoberfest, hacktoberfest-accepted

#269 Removed jQuery and other dependencies that relied on jQuery
  Freshworks-Samples/Freshservice/onclick_alerts/app/app.js
  Freshworks-Samples/Freshservice/onclick_alerts/app/content.html
  Freshworks-Samples/Freshservice/onclick_alerts/app/modal.css
  Freshworks-Samples/Freshservice/onclick_alerts/app/modal.js
  Freshworks-Samples/Freshservice/onclick_alerts/app/style.css
  Freshworks-Samples/Freshservice/onclick_alerts/app/template.html
Labels: Hacktoberfest, hacktoberfest-accepted
