Repository freshworks/marketplace-sample-apps, pull requests merged in 2021-06, with the labels that each got.

#340 [DEVREL-1180] Refactor: Ticket-merger Freshdesk sample-app
  Demo-Apps/ticket_merger/.gitignore
  Demo-Apps/ticket_merger/config/iparam_test_data.json
  Demo-Apps/ticket_merger/config/iparams.json
  Demo-Apps/ticket_merger/server/server.js
  Demo-Apps/ticket_merger/test/test.js
Labels: Enzymes

#332 [DEVREL-1153] feat(sentimental-jeff-app) update custom field
  Demo-Apps/sentimental_jeff_app/README.md
  Demo-Apps/sentimental_jeff_app/app/app.js
  Demo-Apps/sentimental_jeff_app/app/constant.js
  Demo-Apps/sentimental_jeff_app/app/constants.js
  Demo-Apps/sentimental_jeff_app/app/emoticons.js
  Demo-Apps/sentimental_jeff_app/app/freshdesk_logo.png
  Demo-Apps/sentimental_jeff_app/app/style.css
  Demo-Apps/sentimental_jeff_app/app/template.html
  Demo-Apps/sentimental_jeff_app/config/assets/iparams.js
  Demo-Apps/sentimental_jeff_app/config/iparam_test_data.json
  Demo-Apps/sentimental_jeff_app/config/iparams.json
  Demo-Apps/sentimental_jeff_app/manifest.json
Labels: feature-request

#345 📦 NEW: configuration features - apps
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshdesk/manifest.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-html-freshservice/manifest.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-json-freshdesk/manifest.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-iparams-json-freshservice/manifest.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshdesk/manifest.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/manifest.json
Labels: Sprouts

#313 newhire-onboarding-invites Freshteam Sample App
  Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onAppUninstall.json
  Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onExternalEvent.json
  Freshworks-Samples/App-Development-Features/Serverless-Features/external_events_app/server/test_data/onTicketCreate.json
  Freshworks-Samples/App-Development-Features/Serverless-Features/serverless_overview/serverless_with_multiple_events/server/test_data/onExternalEvent.json
  Freshworks-Samples/App-Development-Features/Serverless-Features/serverless_overview/serverless_with_multiple_events/server/test_data/onTicketCreate.json
  Freshworks-Samples/Freshteam/newhire-onboarding-invites/README.md
  Freshworks-Samples/Freshteam/newhire-onboarding-invites/config/iparams.html
  Freshworks-Samples/Freshteam/newhire-onboarding-invites/config/oauth_config.json
  Freshworks-Samples/Freshteam/newhire-onboarding-invites/manifest.json
  Freshworks-Samples/Freshteam/newhire-onboarding-invites/server/server.js
Labels: Sprouts, freshteam, needs-review
