Repository freshworks/marketplace-sample-apps, pull requests merged in 2021-05, with the labels that each got.

#319 👌 IMPROVE: app life cycle alternative available
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/app/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/app/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/app/icon.svg
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/app/style.css
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/app/yourFirstApp_index.html
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/screenshots/AppOnly.png
  Freshworks-Samples/App-Development-Features/Basic-Features/app_cycle_events/your_first_app/screenshots/panel View - App.png
Labels: Combine

#318 📦 NEW: remove old events method
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/app/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/app/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/app/icon.svg
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/app/style.css
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/app/template.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/app/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/app/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/app/icon.svg
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/app/style.css
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/app/template.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/completed/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/app/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/app/freshdesk_logo.png
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/app/icon.svg
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/app/style.css
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/app/template.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api/start/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/app/index.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/app/styles/styles.css
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/screenshots/2.png
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app/screenshots/demo.gif
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/app/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/app/template.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/config/iparam_test_data.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2/screenshots/interceptingCloseOnNoTags.gif
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/README.md
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/app/scripts/app.js
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/app/template.html
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/config/iparams.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/manifest.json
  Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app/screenshots/appViewBig.gif
Labels: Combine

#307 📦 NEW: app setup and external events
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/README.md
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/app/ticket_background.html
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/config/iparams.json
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/manifest.json
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/screenshots/appsetup-1.png
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/screenshots/appsetup-2.png
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/screenshots/ext-events.png
  Freshworks-Samples/App-Development-Features/Serverless-Features/app-setup-and-external-events-freshdesk/server/server.js
Labels: Combine

#317 📦 NEW: merge conflict resolved | Notes reminder app
  Demo-Apps/notes_reminder/app/app.js
  Demo-Apps/notes_reminder/app/note_reminder_index.html
  Demo-Apps/notes_reminder/app/style.css
  Demo-Apps/notes_reminder/app/template.html
  Demo-Apps/notes_reminder/manifest.json
  Demo-Apps/notes_reminder/server/server.js
Labels: Combine

#311 Add: Config-Placeholders-Freshservice sample app
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/README.md
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/styles/images/aeroplane.svg
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/styles/images/helicopter.svg
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/asset_details_page/asset_sidebar.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/change_details_page/change_background.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/change_details_page/change_sidebar.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/contact_details_page/contact_sidebar.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/global_navigation_pane/full_page_app.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/new_change_page/new_change_background.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/new_change_page/new_change_sidebar.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/new_ticket_page/new_ticket_background.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/new_ticket_page/new_ticket_sidebar.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/ticket_details_page/ticket_background.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/ticket_details_page/ticket_requester_info.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/ticket_details_page/ticket_sidebar.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/app/views/ticket_details_page/ticket_top_navigation.html
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/config/iparams.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/manifest.json
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/asset_sidebar.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/change_sidebar.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/contact_sidebar.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/fullpage.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/new_change_sidebar.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/new_ticket_sidebar.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/ticket_requester_info.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/ticket_sidebar.png
  Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshservice/screenshots/ticket_top_navigation.png
Labels: Sprouts

#337 [DEVREL-1181] Refactor: Twilio SMS
  Demo-Apps/twilio_sms/app/app.js
  Demo-Apps/twilio_sms/app/template.html
  Demo-Apps/twilio_sms/config/iparam_test_data.json
  Demo-Apps/twilio_sms/server/server.js
  Demo-Apps/twilio_sms/server/test_data/onContactCreate.json
  Demo-Apps/twilio_sms/server/test_data/onContactUpdate.json
  Demo-Apps/twilio_sms/server/test_data/onConversationCreate.json
  Demo-Apps/twilio_sms/server/test_data/onTicketCreate.json
  Demo-Apps/twilio_sms/server/test_data/onTicketUpdate.json
  Demo-Apps/twilio_sms_freshdesk/README.md
  Demo-Apps/twilio_sms_freshdesk/app/index.html
  Demo-Apps/twilio_sms_freshdesk/app/scripts/app.js
  Demo-Apps/twilio_sms_freshdesk/app/styles/images/icon.svg
  Demo-Apps/twilio_sms_freshdesk/app/styles/style.css
  Demo-Apps/twilio_sms_freshdesk/config/iparams.json
  Demo-Apps/twilio_sms_freshdesk/manifest.json
  Demo-Apps/twilio_sms_freshdesk/screenshots/App face.png
  Demo-Apps/twilio_sms_freshdesk/server/server.js
Labels: Enzymes
